name: Test
description: Testing purposes
body:
  - type: textarea
    id: prs-included
    attributes:
      label: PRs included in this release
      description: Please include all the PRs to be included in this release
      render: Markdown
    validations:
      required: true
