name: Bump Version
description: Inspects the git tags to determine the current normal version, and returns the next version number

inputs:
  increment:
    description: |
      Field to increment - major, minor, or, patch (defaults to patch)
    required: false
    default: patch

outputs:
  bump-version:
    description: Incremented version calculated

runs:
  using: node16
  main: dist/index.js
